#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

message="$(cat $1)"
requiredPattern="^(feat:✨|fix:🐛|docs:📚|style:💎|design:💄|test:🚨|refactor:🔨|build:📦|ci:👷|perf:🚀|chore:🔧|rename:🚚|remove:🔥) .*$"
if ! [[ $message =~ $requiredPattern ]];

then
  echo "-"
  echo "-"
  echo "-"
  echo "🚨 잘못된 커밋 메세지! 😕"
  echo "타입: 제목 의 형식으로 제목을 아래 공백줄에 작성"
  echo "변경사항이 무엇인지 명확히 작성"
  echo "- 사용 가능한 타입 -"
  echo "feat:✨ 새로운 기능 추가"
  echo "fix:🐛 버그 수정"
  echo "docs:📚 문서 수정"
  echo "style:💎 코드 스타일 변경 (코드 포매팅, 세미콜론 누락 등)"
  echo "design:💄 사용자 UI 디자인 변경 (CSS 등)"
  echo "test:🚨 테스트 코드, 리팩토링 (Test Code)"
  echo "refactor:🔨 리팩토링 (Production Code)"
  echo "build:📦 빌드 파일 수정"
  echo "ci:👷 CI 설정 파일 수정"
  echo "perf:🚀 성능 개선"
  echo "chore:🔧 자잘한 수정이나 빌드 업데이트"
  echo "rename:🚚 파일 혹은 폴더명을 수정만 한 경우"
  echo "remove:🔥 파일을 삭제만 한 경우"
  echo "-"
  echo "예) feat:✨ 로그인 기능 추가"
  echo "-"
  echo "커밋 메세지:"
  echo $message
  echo "-"
  exit 1
fi

